- name: "Common Roles"
  hosts: all
  roles:
    - role: account
      tags:
        - account
    - role: docker
      tags:
        - docker
    - role: git
      tags:
        - git

- name: "Load Balancer"
  hosts: load_balancer
  roles:
    - role: nginx
      tags:
        - nginx
    - role: certbot
      tags:
        - certbot
