- name: "Common Roles"
  hosts: all
  roles:
    - role: account

- name: "Load Balancer"
  hosts: load_balancer
  roles:
    - role: certbot
      tags:
        - certbot
    - role: nginx
      tags:
        - nginx
