- name: "Common Roles"
  hosts: all
  roles:
    - role: account
      tags:
        - account
    - role: docker
      tags:
        - docker

- name: "Load Balancer"
  hosts: load_balancer
  roles:
    - role: certbot
      tags:
        - certbot
    - role: nginx
      tags:
        - nginx
