- name: "Bootstrapping Layer Tasks for Vagrant"
  hosts: default
  vars:
    ansible_connection: local
    administrators:
      - ndxbn
  roles:
    - role: account
    - role: network
      tags:
        - network
