- name: "install development tools"
  become: true
  when: ansible_os_family == 'Debian'
  package:
    name:
      - build-essential
      # Ubuntu has `/etc/mime.types` by default.

- name: "install development tools"
  become: true
  when: ansible_os_family == 'RedHat'
  package:
    name:
      - "@Development Tools"
      # /etc/mime.types
      - mailcap
