- name: "create administrator account"
  loop: "{{ administrators }}"
  user:
    name: "{{ item }}"
    state: present

- name: "administrators belong to adm and sudo groups on Ubuntu"
  when: ansible_os_family == 'Debian'
  loop: "{{ administrators }}"
  user:
    name: "{{ item }}"
    state: present
    groups:
      - adm
      - sudo

- name: "administrators belong to wheel groups on CentOS"
  when: ansible_os_family == 'RedHat'
  loop: "{{ administrators }}"
  user:
    name: "{{ item }}"
    state: present
    groups:
      - wheel

- name: "allow sudo command without password for administrators"
  loop: "{{ administrators }}"
  template:
    src: administrator.sudoers_config.j2
    dest: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: root
    mode: 0400

- name: "add administrator's authorized keys from github.com"
  loop: "{{ administrators }}"
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
