# ndxbn.tokyo Local DNS can resolve these hosts.
all:
  vars:
    # In most cases, I use Ubuntu LTS
    ansible_python_interpreter: /usr/bin/python3

  children:
    #
    application:
      hosts:
        server01:
    #
    load_balancer:
      hosts:
        server01:
    ssl_certification:
      hosts:
        server01:
    #
    jetbrains:
      hosts:
        server01:
    sanabutton2:
      hosts:
        server01:
