# ndxbn.tokyo Local DNS can resolve these hosts.
all:
  children:
    #
    application:
      hosts:
        server01:
    #
    load_balancer:
      hosts:
        server01:
    ssl_certification:
      hosts:
        server01:
    #
    sanabutton2:
      hosts:
        server01:
