- name: "add ansible-inventory host records into /etc/hosts"
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {% if 'ansible_host' in hostvars[host] %}
      {{ hostvars[host]['ansible_host'] }}  {{ host }}
      {% endif %}
      {% endfor %}
